import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextAuthSessionProvider from "./SessionProvider";
import Header from "./Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextAuthSessionProvider>
          <Header />
          <main className="min-h-[70vh] px-4 sm:px-8 py-8">{children}</main>
          <footer className="w-full bg-zinc-900 text-white py-4 px-8 text-center text-sm mt-12">
            &copy; {new Date().getFullYear()} E-Shop. All rights reserved.
          </footer>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
