import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import NextAuthSessionProvider from "./SessionProvider";
import Header from "./Header";
import { CartProvider } from "./CartProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SiteLayout({ children }: { children: React.ReactNode }) {
  return (
    <CartProvider>
      <NextAuthSessionProvider>
        <Header />
        <main className="min-h-[70vh] px-4 sm:px-8 py-8">{children}</main>
        <footer className="w-full bg-zinc-100 text-zinc-700 py-4 px-8 text-center text-sm mt-12 border-t border-zinc-200">
          &copy; 2024 E-Shop. All rights reserved.
        </footer>
      </NextAuthSessionProvider>
    </CartProvider>
  );
} 